routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\ItemController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\CustomerController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// User Akses
Route::middleware('auth')->group(function() {
    // Carts
    Route::get('mycart', [CartController::class, 'mycart'])->name('mycart');

    Route::get('cart/{item}/add', [CartController::class, 'addToCart'])->name('cart.add');
    Route::get('cart/{rowId}/addQty', [CartController::class, 'increase_item'])->name('cart.addQuantity');
    Route::get('cart/{rowId}/minQty', [CartController::class, 'decrease_item'])->name('cart.minQuantity');
    Route::get('cart/{item}/remove', [CartController::class, 'remove_from_cart'])->name('cart.remove');
    Route::get('cart/reset', [CartController::class, 'cart_reset'])->name('cart.clear');

    // Checkout
    Route::get('checkout', [CheckoutController::class, 'index'])->name('checkout.page');
    Route::post('checkout/order', [CheckoutController::class, 'order'])->name('checkout.order');

    // Customer
    Route::get('myorder',[CustomerController::class, 'myorder'])->name('myorder');
    Route::get('myorder/{myOrder}/detail',[CustomerController::class, 'detail'])->name('myorder-detail');

});


// Admin Akses
Route::group(['prefix' => 'admin'], function() {

    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::group(['prefix' => 'item' ,'as' => 'item.'], function() {
        Route::get('/', [ItemController::class, 'manage'])->name('manage');
        Route::get('/create', [ItemController::class, 'create'])->name('create');
        Route::post('/store', [ItemController::class, 'store'])->name('store');
        Route::get('/{item:slug}/edit', [ItemController::class, 'edit'])->name('edit');
        Route::put('{item:slug}/update', [ItemController::class, 'update'])->name('update');
        Route::delete('/{item:slug}/delete', [ItemController::class, 'delete'])->name('delete');
        Route::get('/{item:slug}/detail', [ItemController::class, 'detail'])->name('detail');
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
        Route::get('/', [OrderController::class, 'manage'])->name('manage');
        Route::get('/{order}/detail', [OrderController::class, 'detail'])->name('detail');
        Route::get('/{order}/editShipped', [OrderController::class, 'edit_shipped'])->name('edit');
        Route::put('/{order}/shipped', [OrderController::class, 'shipped'])->name('shipped');
    });

    Route::group(['prefix' => 'gallery', 'as' => 'gallery.'], function() {
        Route::get('/manage', [GalleryController::class, 'manage'])->name('manage');
        Route::get('/add', [GalleryController::class, 'add'])->name('add');
        Route::post('/upload', [GalleryController::class, 'upload'])->name('upload');
        Route::get('/{gallery:slug}/edit', [GalleryController::class, 'edit'])->name('edit');
        Route::put('/{gallery:slug}/update', [GalleryController::class, 'update'])->name('update');
        Route::delete('/{gallery:slug}/delete', [GalleryController::class, 'delete'])->name('delete');
    });


});

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug', 'image', 'price', 'description', 'quantity', 'isAvailable'];


}

app/Http/Controllers/Admin/ItemController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Item;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ItemController extends Controller
{
    public function manage()
    {
        $items = Item::latest()->get();
        return view('admin.item.manage', compact('items'));
    }

    public function create()
    {
        return view('admin.item.create-item');
    }

    public function detail(Item $item)
    {
        return view('admin.item.detail-item', compact('item'));
    }

    public function store(Request $request)
    {
        if ($request->hasFile('image')) {
            $imageFile = $request->image;
            $itemImage = uniqid(). '_' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path(). '/api/images/items/', $itemImage);
        }
        else {
            $itemImage = null;
        }

        $item = Item::create([
            'name' => request('name'),
            'slug' => Str::slug(request('name')),
            'image' => $itemImage,
            'price' => request('price'),
            'quantity' => request('quantity'),
            'description' => request('description'),
        ]);

        return redirect()->route('item.manage')->with('message', 'Item Created Succesfully');
    }

    public function edit(Item $item)
    {
        return view('admin.item.edit-item', compact('item'));
    }

    public function update(Item $item, Request $request)
    {
        $itemImage = $item->image;
        $pathImage = public_path(). '/api/images/items/'.$item->image;

        if ($request->hasFile('image')) {
            File::delete($pathImage);
            $imageFile = $request->image;
            $itemImage = uniqid(). '_' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path(). '/api/images/items/', $itemImage);
        } elseif ($item->image) {
            $itemImage = $itemImage;
        }
        else {
            $itemImage = null;
        }

        $item->update([
            'name' => request('name'),
            'slug' => Str::slug(request('name')),
            'image' => $itemImage,
            'price' => request('price'),
            'quantity' => request('quantity'),
            'description' => request('description'),
            'isAvailable' => request()->input('isAvailable') ? true : false,
        ]);

        return redirect()->route('item.manage')->with('message', 'Item Updated Succesfully');
    }

    public function delete(Item $item)
    {
        $pathImage = public_path(). '/api/images/items/'.$item->image;
        File::delete($pathImage);
        $item->delete();

        return back()->with('message-danger', 'Item Deleted Succesfully');
    }
}

app/Http/Controllers/Api/ItemController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\ItemResource;
use App\Models\Item;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class ItemController extends Controller
{
    public function manage()
    {
        $items = Item::all();
        $itemsResource = ItemResource::collection($items);

        return $this->sendResponse($itemsResource, 'Get Items Successfully!');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:items,name,',
            'image' => 'nullable|image|mimes:png,jpg,jpeg,gift',
            'price' => 'required',
            'quantity' => 'required',
            'description' => 'required'
        ]);

        if ($validator->fails()) {
            return $this->sendError('Validation Error', $validator->errors());
        }

        $imageFile = $request->image;
        $itemImage = uniqid(). '_' . $imageFile->getClientOriginalExtension();
        $imageFile->move(public_path(). '/api/images/items/', $itemImage);

        // $input = $request->all();
        // $input['slug'] = Str::slug($input['name']);
        // $input['image'] = $itemImage;

        // $item = Item::create($input);
        $item = Item::create([
            'name' => request('name'),
            'slug' => Str::slug(request('name')),
            'image' => $itemImage,
            'price' => request('price'),
            'quantity' => request('quantity'),
            'description' => request('description'),
        ]);

        return $this->sendResponse(new ItemResource($item), 'Item Created Successfully!');
    }

    public function detail($id)
    {
        $item = Item::find($id);

        if (!empty($item)) {
            return $this->sendResponse(new ItemResource($item), 'Get Item ' .$item->name. ' Succesfully');
        }
        else {
            return $this->sendError('Item Not Found');
        }
    }

    public function update(Item $item, Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:items,name,'. $item->id,
            'image' => 'nullable|image|mimes:png,jpg,jpeg,gift',
            'price' => 'required',
            'quantity' => 'required',
            'description' => 'required'
        ]);

        if ($validator->fails()) {
            return $this->sendError('Validation Update Error', $validator->errors());
        }

        $itemImage = $item->image;
        $pathImage = public_path(). '/api/images/items/'.$item->image;

        if ($request->hasFile('image')) {
            File::delete($pathImage);
            $imageFile = $request->image;
            $itemImage = uniqid(). '_' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path(). '/api/images/items', $itemImage);
        }
        elseif ($item->image) {
            $itemImage = $item->image;
        }
        else {
            $itemImage = null;
        }

        $item->update([
            'name' => request('name'),
            'slug' => Str::slug(request('name')),
            'image' => $itemImage,
            'price' => request('price'),
            'quantity' => request('quantity'),
            'description' => request('description'),
            'isAvailable' => request()->input('isAvailable') ? true : false,
        ]);

        return $this->sendResponse(new ItemResource($item), 'Item Updated Successfully!');
    }

    public function delete(Item $item)
    {
        $pathImage = public_path(). '/api/images/items/'.$item->image;

        File::delete($pathImage);
        $item->delete();

        return $this->sendResponse($item->name, 'Item Deleted Successfully!');
    }
}

resources/views/admin/item/create-item.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card card-seccond">
        <div class="card-header">
          <h3 class="card-title">Add Item</h3>
        </div>
        <form method="post" action="{{ route('item.store') }}" enctype="multipart/form-data">
        @csrf
          <div class="card-body">
            <div class="form-group">
              <label for="name">Product Item</label>
              <input type="text" class="form-control" name="name" id="name" placeholder="Item Product" value="{{ old('name') }}">
              @error('name')
                <div class="mt-2 text-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
                <label for="image">Item Image</label>
                <div class="input-group">
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" name="image" id="image">
                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                  </div>
                  <div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                  </div>
                </div>
                @error('image')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
              </div>
            <div class="form-group">
                <label for="name">Price</label>
                <input type="number" class="form-control" name="price" id="price" placeholder="Price" value="{{ old('price') }}">
                @error('price')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="name">Quantity Item</label>
                <input type="number" class="form-control" name="quantity" id="quantity" placeholder="Quantity Item" value="{{ old('quantity') }}">
                @error('quantity')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="name">Description</label>
                <textarea class="form-control" rows="3" name="description" id="description" placeholder="Description ..."></textarea>
                @error('description')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div>
            {{-- <div class="form-group">
                <label>Sub Category</label>
                <select class="form-control" name="subcategory" id="subcategory" style="width: 100%;">
                  @foreach($subcategories as $categories)
                  <option value="{{ $categories->id }}">{{ $categories->name }}</option>
                  @endforeach
                </select>
                @error('subcategory')
                    <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div> --}}
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-info btn-sm">Submit</button>
          </div>
        </form>
      </div>
    </div>
</div>
@endsection

resources/views/admin/item/detail-item.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="card card-solid">
    <div class="card-body">
      <div class="row">
        <div class="col-12 col-sm-6">
          <h3 class="d-inline-block d-sm-none">{{ $item->name }}</h3>
          <div class="col-12">
            <img src="{{ asset('/api/images/items/'.$item->image) }}" class="product-image" alt="Product Image">
          </div>
          <div class="col-12 product-image-thumbs">
            @for ($image = 0; $image <= 3; $image++)
            <div class="product-image-thumb active">
                <img src="{{ asset('/api/images/items/'.$item->image) }}" alt="Product Image">
            </div>
            @endfor
          </div>
        </div>
        <div class="col-12 col-sm-6">
          <h3 class="my-3">{{ $item->name }}</h3>
          <p>{{ $item->description }}</p>

          <hr>
          <h4 class="my-3">Stock</h4>
                @if ($item->isAvailable == '1')
                <span class="text-md badge bg-success">
                    Tersedia
                </span>

                @else
                <span class="text-md badge bg-danger">
                    Tidak Tersedia
                </span>
                @endif

          <h4 class="mt-3">Quantity</h4>
          <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-default text-center">
              <input type="radio" name="color_option" id="color_option_b1" autocomplete="off">
              <span class="text-md">{{ $item->quantity }}</span>
              <br>
              Items
            </label>
          </div>

          <div class="bg-gray py-2 px-3 mt-4">
            <h2 class="mb-0">
              Rp.{{ $item->price }}
            </h2>
            <h4 class="mt-0">
              <small>Ex Tax: Rp.{{ $item->price * 1.2 }} </small>
            </h4>
          </div>

          <div class="mt-4 product-share">
            <a href="#" class="text-blue">
              <i class="fab fa-facebook-square fa-2x"></i>
            </a>
            <a href="#" class="text-info">
              <i class="fab fa-twitter-square fa-2x"></i>
            </a>
            <a href="#" class="text-red">
              <i class="fas fa-envelope-square fa-2x"></i>
            </a>
            <a href="#" class="text-yellow">
              <i class="fas fa-rss-square fa-2x"></i>
            </a>
          </div>

        </div>
      </div>
      <div class="row mt-4">
        <nav class="w-100">
          <div class="nav nav-tabs" id="product-tab" role="tablist">
            <a class="nav-item nav-link active" id="product-desc-tab" data-toggle="tab" href="#product-desc" role="tab" aria-controls="product-desc" aria-selected="true">Description</a>
            <a class="nav-item nav-link" id="product-comments-tab" data-toggle="tab" href="#product-comments" role="tab" aria-controls="product-comments" aria-selected="false">Comments</a>
            <a class="nav-item nav-link" id="product-rating-tab" data-toggle="tab" href="#product-rating" role="tab" aria-controls="product-rating" aria-selected="false">Rating</a>
          </div>
        </nav>
        <div class="tab-content p-3" id="nav-tabContent">
            <div class="tab-pane fade show active" id="product-desc" role="tabpanel" aria-labelledby="product-desc-tab"> {{ $item->description }}
            </div>
            <div class="tab-pane fade" id="product-comments" role="tabpanel" aria-labelledby="product-comments-tab">
            </div>
            <div class="tab-pane fade" id="product-rating" role="tabpanel" aria-labelledby="product-rating-tab">
            </div>
        </div>
      </div>
    </div>
    <!-- /.card-body -->
</div>
@endsection

resources/views/admin/item/edit-item.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card card-seccond">
        <div class="card-header">
          <h3 class="card-title">Edit Item</h3>
        </div>
        <form method="post" action="{{ route('item.update', $item) }}" enctype="multipart/form-data">
        @csrf
        @method('put')
          <div class="card-body">
            <div class="form-group">
              <label for="name">Product Item</label>
              <input type="text" class="form-control" name="name" id="name" placeholder="Item Product" value="{{ old('name', $item->name) }}">
              @error('name')
                <div class="mt-2 text-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
                <label for="image">Item Image</label>
                <div class="mb-3">
                    <img src="{{ asset('/api/images/items/'.$item->image) }}" alt="" style="width: 170px;" height="120px" class="img-rounded">
                </div>
                <div class="input-group">
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" name="image" id="image">
                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                  </div>
                  <div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                  </div>
                </div>
                @error('image')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
              </div>
            <div class="form-group">
                <label for="name">Price</label>
                <input type="number" class="form-control" name="price" id="price" placeholder="Price" value="{{ old('name', $item->price) }}">
                @error('price')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="name">Quantity Item</label>
                <input type="number" class="form-control" name="quantity" id="quantity" placeholder="Quantity Item" value="{{ old('quantity', $item->quantity) }}">
                @error('quantity')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <div class="form-check">
                <input class="form-check-input" name="isAvailable" type="checkbox" value="1" {{ $item->isAvailable == 1 ? 'checked': '' }}>
                <label class="form-check-label">Tersedia</label>
                </div>
            </div>
            <div class="form-group">
                <label for="name">Description</label>
                <textarea class="form-control" rows="3" name="description" id="description" placeholder="description ...">{{ $item->description }}</textarea>
                @error('kota')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-info btn-sm">Update</button>
          </div>
        </form>
      </div>
    </div>
</div>
@endsection

resources/views/admin/item/manage.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        @include('layouts.message')
        <div class="card">
          <div class="card-header">
            <div class="card-title">
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                      <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                      <div class="input-group-append">
                        <button type="submit" class="btn btn-default">
                          <i class="fas fa-search"></i>
                        </button>
                      </div>
                    </div>
                </div>
            </div>

            <div class="card-tools">
                <span class="badge">
                    <a href="{{ route('item.create') }}" type="button" class="btn btn-info btn-sm">Create</a>
                </span>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th style="width: 10px">No</th>
                  <th>Item Product</th>
                  <th>Image</th>
                  <th>Price</th>
                  <th>Quantity</th>
                  <th>Description</th>
                  <th>Stock Item</th>
                  <th style="width: 40px">Manage</th>
                </tr>
              </thead>
              <tbody>
                @foreach($items as $item)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $item->name }}</td>
                    <td>
                        {{ Str::limit($item->image, 10) }}
                    </td>
                    <td>Rp.{{ $item->price }}</td>
                    <td>{{ $item->quantity }}</td>
                    <td>{{ Str::limit($item->description, 30) }}</td>
                    <td>
                        @if ($item->isAvailable == '1')
                        <span class="badge bg-success">Tersedia</span>

                        @else
                        <span class="badge bg-danger">Tidak Tersedia</span>
                        @endif
                    </td>
                    <td class="d-flex" style="column-gap: 5px">
                        <a href="{{ route('item.detail', $item) }}" type="button" class="btn btn-success btn-sm">Detail</a>
                        <a href="{{ route('item.edit', $item) }}" type="button" class="btn btn-info btn-sm">Edit</a>
                        <form action="{{ route('item.delete', $item) }}" method="post">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
@endsection