routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\ItemController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\CustomerController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// User Akses
Route::middleware('auth')->group(function() {
    // Carts
    Route::get('mycart', [CartController::class, 'mycart'])->name('mycart');

    Route::get('cart/{item}/add', [CartController::class, 'addToCart'])->name('cart.add');
    Route::get('cart/{rowId}/addQty', [CartController::class, 'increase_item'])->name('cart.addQuantity');
    Route::get('cart/{rowId}/minQty', [CartController::class, 'decrease_item'])->name('cart.minQuantity');
    Route::get('cart/{item}/remove', [CartController::class, 'remove_from_cart'])->name('cart.remove');
    Route::get('cart/reset', [CartController::class, 'cart_reset'])->name('cart.clear');

    // Checkout
    Route::get('checkout', [CheckoutController::class, 'index'])->name('checkout.page');
    Route::post('checkout/order', [CheckoutController::class, 'order'])->name('checkout.order');

    // Customer
    Route::get('myorder',[CustomerController::class, 'myorder'])->name('myorder');
    Route::get('myorder/{myOrder}/detail',[CustomerController::class, 'detail'])->name('myorder-detail');

});


// Admin Akses
Route::group(['prefix' => 'admin'], function() {

    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::group(['prefix' => 'item' ,'as' => 'item.'], function() {
        Route::get('/', [ItemController::class, 'manage'])->name('manage');
        Route::get('/create', [ItemController::class, 'create'])->name('create');
        Route::post('/store', [ItemController::class, 'store'])->name('store');
        Route::get('/{item:slug}/edit', [ItemController::class, 'edit'])->name('edit');
        Route::put('{item:slug}/update', [ItemController::class, 'update'])->name('update');
        Route::delete('/{item:slug}/delete', [ItemController::class, 'delete'])->name('delete');
        Route::get('/{item:slug}/detail', [ItemController::class, 'detail'])->name('detail');
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
        Route::get('/', [OrderController::class, 'manage'])->name('manage');
        Route::get('/{order}/detail', [OrderController::class, 'detail'])->name('detail');
        Route::get('/{order}/editShipped', [OrderController::class, 'edit_shipped'])->name('edit');
        Route::put('/{order}/shipped', [OrderController::class, 'shipped'])->name('shipped');
    });

    Route::group(['prefix' => 'gallery', 'as' => 'gallery.'], function() {
        Route::get('/manage', [GalleryController::class, 'manage'])->name('manage');
        Route::get('/add', [GalleryController::class, 'add'])->name('add');
        Route::post('/upload', [GalleryController::class, 'upload'])->name('upload');
        Route::get('/{gallery:slug}/edit', [GalleryController::class, 'edit'])->name('edit');
        Route::put('/{gallery:slug}/update', [GalleryController::class, 'update'])->name('update');
        Route::delete('/{gallery:slug}/delete', [GalleryController::class, 'delete'])->name('delete');
    });


});

resources/views/layouts/partial-admin/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="i{{ route('dashboard') }}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">About</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
</nav>

resources/views/layouts/partial-admin/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="/admin/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Black Salad</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/admin/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Admin Black Salad</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ route('dashboard') }}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          <li class="nav-header">Admin</li>
          <li class="nav-item">
            <a href="{{ route('item.manage') }}" class="nav-link">
              <i class="nav-icon fas fa-columns"></i>
              <p>
                Item
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('order.manage') }}" class="nav-link">
            <i class="nav-icon far fa-calendar-alt"></i>
              <p>
                Order
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('gallery.manage') }}" class="nav-link">
              <i class="nav-icon fas fa-columns"></i>
              <p>
                Gallery
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link">
              <i class="nav-icon far fa-calendar-alt"></i>
              <p>
                 Cooming Soon..
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                 Cooming Soon..
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>