routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\ItemController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\CustomerController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// User Akses
Route::middleware('auth')->group(function() {
    // Carts
    Route::get('mycart', [CartController::class, 'mycart'])->name('mycart');

    Route::get('cart/{item}/add', [CartController::class, 'addToCart'])->name('cart.add');
    Route::get('cart/{rowId}/addQty', [CartController::class, 'increase_item'])->name('cart.addQuantity');
    Route::get('cart/{rowId}/minQty', [CartController::class, 'decrease_item'])->name('cart.minQuantity');
    Route::get('cart/{item}/remove', [CartController::class, 'remove_from_cart'])->name('cart.remove');
    Route::get('cart/reset', [CartController::class, 'cart_reset'])->name('cart.clear');

    // Checkout
    Route::get('checkout', [CheckoutController::class, 'index'])->name('checkout.page');
    Route::post('checkout/order', [CheckoutController::class, 'order'])->name('checkout.order');

    // Customer
    Route::get('myorder',[CustomerController::class, 'myorder'])->name('myorder');
    Route::get('myorder/{myOrder}/detail',[CustomerController::class, 'detail'])->name('myorder-detail');

});


// Admin Akses
Route::group(['prefix' => 'admin'], function() {

    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::group(['prefix' => 'item' ,'as' => 'item.'], function() {
        Route::get('/', [ItemController::class, 'manage'])->name('manage');
        Route::get('/create', [ItemController::class, 'create'])->name('create');
        Route::post('/store', [ItemController::class, 'store'])->name('store');
        Route::get('/{item:slug}/edit', [ItemController::class, 'edit'])->name('edit');
        Route::put('{item:slug}/update', [ItemController::class, 'update'])->name('update');
        Route::delete('/{item:slug}/delete', [ItemController::class, 'delete'])->name('delete');
        Route::get('/{item:slug}/detail', [ItemController::class, 'detail'])->name('detail');
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
        Route::get('/', [OrderController::class, 'manage'])->name('manage');
        Route::get('/{order}/detail', [OrderController::class, 'detail'])->name('detail');
        Route::get('/{order}/editShipped', [OrderController::class, 'edit_shipped'])->name('edit');
        Route::put('/{order}/shipped', [OrderController::class, 'shipped'])->name('shipped');
    });

    Route::group(['prefix' => 'gallery', 'as' => 'gallery.'], function() {
        Route::get('/manage', [GalleryController::class, 'manage'])->name('manage');
        Route::get('/add', [GalleryController::class, 'add'])->name('add');
        Route::post('/upload', [GalleryController::class, 'upload'])->name('upload');
        Route::get('/{gallery:slug}/edit', [GalleryController::class, 'edit'])->name('edit');
        Route::put('/{gallery:slug}/update', [GalleryController::class, 'update'])->name('update');
        Route::delete('/{gallery:slug}/delete', [GalleryController::class, 'delete'])->name('delete');
    });


});

app/Models/Gallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'slug', 'image'];
}

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Gallery;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class GalleryController extends Controller
{
    public function manage()
    {
        $galleries = Gallery::all();
        return view('admin.gallery.manage', compact('galleries'));
    }

    public function add()
    {
        return view('admin.gallery.add-gallery');
    }

    public function upload(Request $request)
    {
        if ($request->hasFile('image')) {
            $imageFile = $request->image;
            $galleryImage = uniqid(). '_' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path(). '/api/images/galleries/', $galleryImage);
        }

        $gallery = Gallery::create([
            'title' => request('title'),
            'slug' => Str::slug(request('title')),
            'image' => $galleryImage,
        ]);

        return redirect()->route('gallery.manage')->with('message',''. $gallery->title.' Added Succesfully');
    }

    public function edit(Gallery $gallery)
    {
        return view('admin.gallery.edit-gallery', compact('gallery'));
    }

    public function update(Request $request, Gallery $gallery)
    {
        $galleryImage = $gallery->image;
        $pathImage = public_path(). '/api/images/galleries/'. $gallery->image;

        if ($request->hasFile('image')) {
            File::delete($pathImage);
            $imageFile = $request->image;
            $galleryImage = uniqid(). '_' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path(). '/api/images/galleries/', $galleryImage);
        }
        elseif ($gallery->image) {
            $galleryImage = $gallery->image;
        }
        else {
            $galleryImage = null;
        }

        $gallery->update([
            'title' => request('title'),
            'slug' => Str::slug(request('title')),
            'image' => $galleryImage,
        ]);

        return redirect()->route('gallery.manage')->with('message',''. $gallery->title.' Update Succesfully');
    }

    public function delete(Gallery $gallery)
    {
        $galleryImage = public_path(). '/api/images/galleries/'. $gallery->image;
        File::delete($galleryImage);
        $gallery->delete();

        return back()->with('message', ''.$gallery->title. ' Deleted Succesfully');;
    }
}

app/Http/Controllers/Api/GalleryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\GalleryResource;
use App\Models\Gallery;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class GalleryController extends Controller
{
    public function manage()
    {
        $galleries = Gallery::all();
        $galleryResource = GalleryResource::collection($galleries);

        return $this->sendResponse($galleryResource, 'Get Galleries Successfully');
    }

    public function upload(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'image' => 'nullable|image|mimes:png,jpg,jpeg,gift',
        ]);

        if ($validator->fails()) {
            return $this->sendError('Validasi Tidak Sesuai', $validator->errors());
        }

        $imageFile = $request->image;
        $galleryImage = uniqid(). '_' . $imageFile->getClientOriginalExtension();
        $imageFile->move(public_path(). '/api/images/galleries/', $galleryImage);

        $gallery = Gallery::create([
            'title' => request('title'),
            'slug' => Str::slug(request('title')),
            'image' => $galleryImage,
        ]);

        return $this->sendResponse(new GalleryResource($gallery), 'Gallery Upload Successfully');
    }

    public function update(Gallery $gallery, Request $request)
    {
        $galleryImage = $gallery->image;
        $pathImage = public_path(). '/api/images/galleries/'. $gallery->image;

        $validator = Validator::make($request->all(), [
            'title' => 'required|unique:galleries,title,'. $gallery->id,
            'image' => 'nullable|image|mimes:png,jpg,jpeg,gift',
        ]);

        if ($validator->fails()) {
            return $this->sendError('Validasi Tidak Sesuai', $validator->errors());
        }

        if ($request->hasFile('image')) {
            File::delete($pathImage);
            $imageFile = $request->image;
            $galleryImage = uniqid(). '_' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path(). '/api/images/galleries/', $galleryImage);
        }
        elseif ($gallery->image) {
            $galleryImage = $gallery->image;
        }
        else {
            $galleryImage = null;
        }

        $gallery->update([
            'title' => request('title'),
            'slug' => Str::slug(request('title')),
            'image' => $galleryImage,
        ]);

        return $this->sendResponse(new GalleryResource($gallery), 'Gallery Updated Successfully');
    }

    public function delete(Gallery $gallery)
    {
        $pathImage = public_path(). '/api/images/galleries/'. $gallery->image;
        File::delete($pathImage);
        $gallery->delete();

        return $this->sendResponse($gallery->title, 'Gallery Deleted Successfully');
    }
}

resources/views/admin/gallery/add-gallery.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card card-seccond">
        <div class="card-header">
          <h3 class="card-title">Add Gallery</h3>
        </div>
        <form method="post" action="{{ route('gallery.upload') }}" enctype="multipart/form-data">
        @csrf
          <div class="card-body">
            <div class="form-group">
              <label for="title">Title</label>
              <input type="text" class="form-control" name="title" id="title" placeholder="Gallery Title" value="{{ old('title') }}">
              @error('title')
                <div class="mt-2 text-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
                <label for="image">Gallery Image</label>
                <div class="input-group">
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" name="image" id="image">
                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                  </div>
                  <div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                  </div>
                </div>
                @error('image')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-info btn-sm">Submit</button>
          </div>
        </form>
      </div>
    </div>
</div>
@endsection

resources/views/admin/gallery/edit-gallery.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card card-seccond">
        <div class="card-header">
          <h3 class="card-title">Add Gallery</h3>
        </div>
        <form method="post" action="{{ route('gallery.update', $gallery) }}" enctype="multipart/form-data">
        @csrf
        @method('put')
          <div class="card-body">
            <div class="form-group">
              <label for="title">Title</label>
              <input type="text" class="form-control" name="title" id="title" placeholder="Gallery Title" value="{{ old('title', $gallery->title) }}">
              @error('title')
                <div class="mt-2 text-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
                <label for="image">Gallery Image</label>
                <div class="mb-3">
                    <img src="{{ asset('/api/images/galleries/'.$gallery->image) }}" alt="" style="width: 170px;" height="120px" class="img-rounded">
                </div>
                <div class="input-group">
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" name="image" id="image">
                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                  </div>
                  <div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                  </div>
                </div>
                @error('image')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-info btn-sm">Update</button>
          </div>
        </form>
      </div>
    </div>
</div>
@endsection

resources/views/admin/gallery/manage.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <div class="card-title">
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                      <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                      <div class="input-group-append">
                        <button type="submit" class="btn btn-default">
                          <i class="fas fa-search"></i>
                        </button>
                      </div>
                    </div>
                </div>
            </div>

            <div class="card-tools">
                <span class="badge">
                    <a href="{{ route('gallery.add') }}" type="button" class="btn btn-info btn-sm">Add</a>
                </span>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <table class="table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Image</th>
                  <th style="width: 40px" class="text-center">Manage</th>
                </tr>
              </thead>
              <tbody>
                @foreach($galleries as $no => $gallery)
                <tr>
                    <td>Gallery {{ $no + 1 }}</td>
                    <td>
                        <img src="{{ asset('/api/images/galleries/'.$gallery->image) }}" alt="" style="width: 170px;" height="120px" class="img-rounded">
                    </td>

                    <td class="d-flex" style="column-gap: 5px">
                        <a href="{{ route('gallery.edit', $gallery) }}" type="button" class="btn btn-success btn-sm">Edit</a>
                        <a href="" type="button" class="btn btn-info btn-sm">View</a>
                        <form action="{{ route('gallery.delete', $gallery) }}" method="post">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>

        </div>
    </div>
</div>
@endsection