routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\ItemController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\CustomerController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// User Akses
Route::middleware('auth')->group(function() {
    // Carts
    Route::get('mycart', [CartController::class, 'mycart'])->name('mycart');

    Route::get('cart/{item}/add', [CartController::class, 'addToCart'])->name('cart.add');
    Route::get('cart/{rowId}/addQty', [CartController::class, 'increase_item'])->name('cart.addQuantity');
    Route::get('cart/{rowId}/minQty', [CartController::class, 'decrease_item'])->name('cart.minQuantity');
    Route::get('cart/{item}/remove', [CartController::class, 'remove_from_cart'])->name('cart.remove');
    Route::get('cart/reset', [CartController::class, 'cart_reset'])->name('cart.clear');

    // Checkout
    Route::get('checkout', [CheckoutController::class, 'index'])->name('checkout.page');
    Route::post('checkout/order', [CheckoutController::class, 'order'])->name('checkout.order');

    // Customer
    Route::get('myorder',[CustomerController::class, 'myorder'])->name('myorder');
    Route::get('myorder/{myOrder}/detail',[CustomerController::class, 'detail'])->name('myorder-detail');

});


// Admin Akses
Route::group(['prefix' => 'admin'], function() {

    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::group(['prefix' => 'item' ,'as' => 'item.'], function() {
        Route::get('/', [ItemController::class, 'manage'])->name('manage');
        Route::get('/create', [ItemController::class, 'create'])->name('create');
        Route::post('/store', [ItemController::class, 'store'])->name('store');
        Route::get('/{item:slug}/edit', [ItemController::class, 'edit'])->name('edit');
        Route::put('{item:slug}/update', [ItemController::class, 'update'])->name('update');
        Route::delete('/{item:slug}/delete', [ItemController::class, 'delete'])->name('delete');
        Route::get('/{item:slug}/detail', [ItemController::class, 'detail'])->name('detail');
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
        Route::get('/', [OrderController::class, 'manage'])->name('manage');
        Route::get('/{order}/detail', [OrderController::class, 'detail'])->name('detail');
        Route::get('/{order}/editShipped', [OrderController::class, 'edit_shipped'])->name('edit');
        Route::put('/{order}/shipped', [OrderController::class, 'shipped'])->name('shipped');
    });

    Route::group(['prefix' => 'gallery', 'as' => 'gallery.'], function() {
        Route::get('/manage', [GalleryController::class, 'manage'])->name('manage');
        Route::get('/add', [GalleryController::class, 'add'])->name('add');
        Route::post('/upload', [GalleryController::class, 'upload'])->name('upload');
        Route::get('/{gallery:slug}/edit', [GalleryController::class, 'edit'])->name('edit');
        Route::put('/{gallery:slug}/update', [GalleryController::class, 'update'])->name('update');
        Route::delete('/{gallery:slug}/delete', [GalleryController::class, 'delete'])->name('delete');
    });


});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'name', 'email', 'address', 'phone', 'city', 'province', 'total', 'payment_gateway', 'shipped'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function itemOrders()
    {
        return $this->hasMany(ItemOrder::class);
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function manage()
    {
        $orders = Order::all();
        return view('admin.order.list', compact('orders'));
    }

    public function detail(Order $order)
    {
        return view('admin.order.order-detail', compact('order'));
    }

    public function edit_shipped(Order $order)
    {
        return view('admin.order.shipped', compact('order'));
    }

    public function shipped(Order $order)
    {
        $order->update([
            'shipped' => request()->input('shipped') ? true : false,
        ]);

        return redirect()->route('order.manage');
    }
}

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\ItemOrderResource;
use App\Http\Resources\OrderResource;
use App\Models\ItemOrder;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function list()
    {
        $orders = Order::all();
        $orderResource = OrderResource::collection($orders);

        return $this->sendResponse($orderResource, 'Get Orders Successfully');
    }

    public function detail(Order $order)
    {
        $itemOrder = ItemOrder::where('order_id', $order->id)->get();

        if (!empty($order)) {
            // return $this->sendResponse(new OrderResource($order), ItemOrderResource::collection($itemOrder),  'Get Order Detail');
            return response()->json([
                'success' => true,
                'message' => 'Get Order Detail',
                'data' => new OrderResource($order),
                'item' => ItemOrderResource::collection($itemOrder),
            ]);

        }
        else {
            return $this->sendError('Order Not Found');
        }
    }

    public function delete(Order $order)
    {
        $order->delete();
        return $this->sendResponse($order->name, 'Order Deleted Successfully!');
    }
}

resources/views/admin/order/list.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <div class="card-title">
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                      <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                      <div class="input-group-append">
                        <button type="submit" class="btn btn-default">
                          <i class="fas fa-search"></i>
                        </button>
                      </div>
                    </div>
                </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <table class="table">
              <thead>
                <tr>
                  <th style="width: 10px">Order ID</th>
                  <th>Customer</th>
                  <th>Address</th>
                  <th>Phone</th>
                  <th>Total</th>
                  <th>Date</th>
                  <th>Dikirim</th>
                  <th style="width: 40px">Manage</th>
                </tr>
              </thead>
              <tbody>
                @foreach($orders as $order)
                <tr>
                    <td>#{{ $order->id }}</td>
                    <td>{{ $order->name }}</td>
                    <td>{{ Str::limit($order->address, 25) }}</td>
                    <td>{{ $order->phone }}</td>
                    <td>Rp.{{ $order->total }}</td>
                    <td>{{ $order->created_at->format('d/m/Y')}}</td>
                    <td>
                        @if ($order->shipped === 1)
                            <span class="badge bg-success">Dikirim</span>
                        @else
                            <span class="badge bg-warning">Proses</span>
                        @endif
                    </td>

                    <td class="d-flex" style="column-gap: 5px">
                        <a href="{{ route('order.edit', $order) }}" type="button" class="btn btn-success btn-sm">Shipped</a>
                        <a href="{{ route('order.detail', $order) }}" type="button" class="btn btn-warning btn-sm">View</a>
                    </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>

          {{-- <div class="card-body p-0">
            <table class="table">
              <thead>
                <tr>
                  <th>Order ID</th>
                  <th>Item</th>
                  <th>Quantity</th>
                  <th style="width: 40px">Manage</th>
                </tr>
              </thead>
              <tbody>
                @foreach($orderItem as $order)
                <tr>
                    <td>{{ $order->order_id }}</td>
                    <td>{{ $order->item_id }}</td>
                    <td>{{ $order->quantity }}</td>
                    <td class="d-flex" style="column-gap: 5px">
                        <a href="" type="button" class="btn btn-info btn-sm">Edit</a>
                        <form action="" method="post">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div> --}}

        </div>
    </div>
</div>
@endsection

resources/views/admin/order/order-detail.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="invoice p-3 mb-3">
            <!-- title row -->
            <div class="row mb-3">
              <div class="col-12">
                <h4>
                  <i class="fas fa-globe"></i> BlackFood, Inc.
                <small class="float-right">Date: {{ $order->created_at->format('d/m/Y') }}</small>
                </h4>
              </div>
              <!-- /.col -->
            </div>
            <!-- info row -->
            <div class="row invoice-info">
              <!-- /.col -->
              <div class="col-sm-6 invoice-col">
                <address>
                  <strong>{{ $order->name }}</strong>
                  <br>
                  {{ $order->address }}
                  <br>
                  Phone: {{ $order->phone }}<br>
                  Email: {{ $order->email }}
                </address>
              </div>
              <!-- /.col -->
              <div class="col-sm-6 invoice-col">
                <b>User Id #{{ $order->user_id }}</b><br>
                <br>
                <b>Order ID:</b> {{ $order->id }}<br>
                <b>Payment Gate:</b> {{ $order->payment_gateway }}<br>
                <b>Satatus:</b> @if ($order->shipped == '1')
                <span class="badge bg-success">Dikirim</span>

                @else
                <span class="badge bg-danger">Prosess</span>
                @endif
              </div>
              <!-- /.col -->
            </div>
        </div>

        <div class="card">
            <div class="card-header">
              <div class="card-title">
                <h4>
                     Order List
                </h4>
                  {{-- <div class="card-tools">
                      <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                          <button type="submit" class="btn btn-default">
                            <i class="fas fa-search"></i>
                          </button>
                        </div>
                      </div>
                  </div> --}}
              </div>
            </div>
            <!-- /.card-header -->

            <div class="card-body p-0">
              <table class="table">
                <thead>
                  <tr>
                    <th>Item</th>
                    <th>Image</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th style="width: 40px">Manage</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($order->itemOrders as $order)
                  <tr>
                      <td>{{ $order->item->name }}</td>
                      <td>
                        {{-- <img src="{{ asset('/api/images/items/'.$item->image) }}" alt="Product Image"> --}}
                        <img src="{{ asset('/api/images/items/'.$order->item->image) }}" alt="" style="width: 150px;" height="100px" class="img-rounded">
                    </td>
                      <td>{{ $order->item->price }}</td>
                      <td>
                        <b>{{ $order->quantity }}</b>
                      </td>
                      <td class="d-flex" style="column-gap: 5px">
                          <a href="" type="button" class="btn btn-info btn-sm">Edit</a>
                          <form action="" method="post">
                              @csrf
                              @method('delete')
                              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                          </form>
                      </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>

          </div>
    </div>
</div>
@endsection

resources/views/admin/order/shipped.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card card-seccond">
        <div class="card-header">
          <h3 class="card-title">Add Gallery</h3>
        </div>
        <form method="post" action="{{  route('order.shipped', $order) }}" enctype="multipart/form-data">
        @csrf
        @method('put')
          <div class="card-body">
            <div class="form-group">
                <div class="form-check">
                <input class="form-check-input" name="shipped" type="checkbox" value="1" {{ $order->shipped == 1 ? 'checked': '' }}>
                <label class="form-check-label">Dikirim</label>
                </div>
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-info btn-sm">Update</button>
          </div>
        </form>
      </div>
    </div>
</div>
@endsection